config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'charts#index'

  resources :artists do
    resources :songs
  end

  resources :charts do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/chart.rb
class Chart < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :chart, optional: :true
  belongs_to :artist, optional: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :charts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :destroy, :edit, :update]


  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else  
      render partial: "form"
    end
  end


  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render partial: "form"
    end
  end

  def edit
    render partial: "form"
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :destroy, :edit, :update]

  def index
    @charts = Chart.all
  end

  def show
  end

  def new
    @chart = Chart.new
    render partial: "form"
  end

  def create
    @chart = Chart.new(chart_params)
    if @chart.save
      redirect_to charts_path
    else
      render partial: "form"
    end
  end

  def destroy
     @chart.destroy
    redirect_to @chart
  end

  def edit
    render partial: "form"
  end

  def update
    if @chart.update(chart_params)
      redirect_to @chart
    else
      render partial: "form"
    end
  end

  private

  def set_chart
    @chart = Chart.find(params[:id])
  end

  def chart_params
    params.require(:chart).permit(:name)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # before_action :set_artist
  before_action :set_chart
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @chart.songs.all
    @songs = @artist.songs.all
  end

  def show
  end
  
  def new
    @song = @chart.songs.new
    render partial: 'form'
  end

  def update
    if @song.update(song_params)
      redirect_to @chart
    else 
      render partial: "form"
    end
  end

  def create
    @song = @chart.songs.new(song_params)
      if @song.save
        redirect_to @chart
      else
        render partial: "form"
      end
  end

  def edit
    render partial: 'form'
  end

  def destroy
    @song.destroy
    redirect_to @chart
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_chart
    @chart = Chart.find(params[:chart_id])
  end

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1> Add New Artist </h1>

<h1><%= @artist.id ? 'Edit Artist' : 'Add Artist' %></h1>
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  
  <%= f.submit %>

<% end %> 

app/views/artists/index.html.erb
<h1>Artists</h1>


<%= link_to 'Add Artist', new_artist_path %>

<% @artists.each do |artist| %>
 <h3><%=link_to artist.name, artist_path(artist) %></h3>
 <% end %> 

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<% @artist.songs.each do |song| %>
  <h5><%= song.title %></h5>
<% end %>

<%= link_to 'Edit Artist', edit_artist_path %>
<%= link_to 'Delete Artist', artist_path, method: :delete %>

app/views/charts/_form.html.erb
<h1> Add New Chart </h1>

<h1><%= @chart.id ? 'Edit Chart' : 'Create Chart' %></h1>
<%= form_for @chart do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  
  <%= f.submit %>

<% end %> 

app/views/charts/index.html.erb
<div class="charts-container">
<h1>Top Music Charts</h1>


<h2>Welcome <%= current_user.first_name %></h2>


<%= link_to "Explore Artists", artists_path, class: "btn black" %>

<div class="chart">

  <% @charts.each do |chart| %>
  
        <h5><%= link_to chart.name, chart_path(chart) %></h5>
   
     <% end %> 


  <%= link_to 'Add New Chart', new_chart_path, class:"btn index-button" %>
  </>
</div>

app/views/charts/new.html.erb
<h1>Charts#new</h1>
<p>Find me in app/views/charts/new.html.erb</p>

app/views/charts/show.html.erb
<h1><%= @chart.name %></h1>


<% @chart.songs.each do |song| %>
  <h4><%=link_to song.title, chart_song_path(@chart, song) %></h4>
<% end %>

<%= link_to 'Edit Chart', edit_chart_path%>
<%= link_to 'Delete Chart', chart_path(@chart), method: :delete%>
<%= link_to 'Add New Song',new_chart_song_path(@chart) %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Charts', charts_path %>
    </li>
    <li>
      <%= link_to 'Artists', artists_path %>
    </li>
    <li>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardS19</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
   <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<h1> Add New Song </h1>

<h1><%= @song.id ? 'Edit Song' : 'Add Song' %></h1>
<%= form_for [@chart, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  
  <%= f.submit %>

<% end %> 

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>


<%= link_to "Edit Song", edit_chart_song_path(@chart, @song) %>
<%= link_to "Delete Song", chart_song_path, method: :delete %>